wget https://github.com/yosyshq/oss-cad-suite-build/releases/download/bucket-windows-x64/windows-x64-apicula.tgz
wget https://github.com/yosyshq/oss-cad-suite-build/releases/download/bucket-windows-x64/windows-x64-avy.tgz
wget https://github.com/yosyshq/oss-cad-suite-build/releases/download/bucket-windows-x64/windows-x64-bitwuzla.tgz
wget https://github.com/yosyshq/oss-cad-suite-build/releases/download/bucket-windows-x64/windows-x64-boolector.tgz
wget https://github.com/yosyshq/oss-cad-suite-build/releases/download/bucket-windows-x64/windows-x64-cvc4.tgz
wget https://github.com/yosyshq/oss-cad-suite-build/releases/download/bucket-windows-x64/windows-x64-cvc5.tgz
wget https://github.com/yosyshq/oss-cad-suite-build/releases/download/bucket-windows-x64/windows-x64-eqy.tgz
wget https://github.com/yosyshq/oss-cad-suite-build/releases/download/bucket-windows-x64/windows-x64-formal.tgz
wget https://github.com/yosyshq/oss-cad-suite-build/releases/download/bucket-windows-x64/windows-x64-gtkwave.tgz
wget https://github.com/yosyshq/oss-cad-suite-build/releases/download/bucket-windows-x64/windows-x64-icestorm.tgz
wget https://github.com/yosyshq/oss-cad-suite-build/releases/download/bucket-windows-x64/windows-x64-imctk.tgz
wget https://github.com/yosyshq/oss-cad-suite-build/releases/download/bucket-windows-x64/windows-x64-iverilog.tgz
wget https://github.com/yosyshq/oss-cad-suite-build/releases/download/bucket-windows-x64/windows-x64-nextpnr-ecp5.tgz
wget https://github.com/yosyshq/oss-cad-suite-build/releases/download/bucket-windows-x64/windows-x64-nextpnr-generic.tgz
wget https://github.com/yosyshq/oss-cad-suite-build/releases/download/bucket-windows-x64/windows-x64-nextpnr-himbaechel.tgz
wget https://github.com/yosyshq/oss-cad-suite-build/releases/download/bucket-windows-x64/windows-x64-nextpnr-ice40.tgz
wget https://github.com/yosyshq/oss-cad-suite-build/releases/download/bucket-windows-x64/windows-x64-nextpnr-machxo2.tgz
wget https://github.com/yosyshq/oss-cad-suite-build/releases/download/bucket-windows-x64/windows-x64-nextpnr-nexus.tgz
wget https://github.com/yosyshq/oss-cad-suite-build/releases/download/bucket-windows-x64/windows-x64-openfpgaloader.tgz
wget https://github.com/yosyshq/oss-cad-suite-build/releases/download/bucket-windows-x64/windows-x64-pono.tgz
wget https://github.com/yosyshq/oss-cad-suite-build/releases/download/bucket-windows-x64/windows-x64-prjoxide.tgz
wget https://github.com/yosyshq/oss-cad-suite-build/releases/download/bucket-windows-x64/windows-x64-prjtrellis.tgz
wget https://github.com/yosyshq/oss-cad-suite-build/releases/download/bucket-windows-x64/windows-x64-pyhdl.tgz
wget https://github.com/yosyshq/oss-cad-suite-build/releases/download/bucket-windows-x64/windows-x64-python3.tgz
wget https://github.com/yosyshq/oss-cad-suite-build/releases/download/bucket-windows-x64/windows-x64-system-resources.tgz
wget https://github.com/yosyshq/oss-cad-suite-build/releases/download/bucket-windows-x64/windows-x64-utils.tgz
wget https://github.com/yosyshq/oss-cad-suite-build/releases/download/bucket-windows-x64/windows-x64-verilator.tgz
wget https://github.com/yosyshq/oss-cad-suite-build/releases/download/bucket-windows-x64/windows-x64-yices.tgz
wget https://github.com/yosyshq/oss-cad-suite-build/releases/download/bucket-windows-x64/windows-x64-yosys.tgz
wget https://github.com/yosyshq/oss-cad-suite-build/releases/download/bucket-windows-x64/windows-x64-yosys-slang-plugin.tgz
wget https://github.com/yosyshq/oss-cad-suite-build/releases/download/bucket-windows-x64/windows-x64-z3.tgz
